---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: helm-controller
spec:
  chart: loki
  repo: https://grafana.github.io/helm-charts
  version: 4.7.0
  targetNamespace: observability
  #  https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  valuesContent: |-
    write:
      replicas: 1
    read:
      replicas: 1
    loki:
      auth_enabled: false