---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: helm-controller
spec:
  chart: loki-stack
  repo: https://grafana.github.io/helm-charts
  version: 2.9.9
  targetNamespace: observability
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  valuesContent: |-