---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keycloak
  namespace: helm-controller
spec:
  chart: keycloak
  repo: https://bhuwanupadhyay.github.io/helm-charts/
  version: 1.0.0
  targetNamespace: kube-addons
  # https://github.com/bhuwanupadhyay/helm-charts/blob/main/charts/keycloak/values.yaml
  valuesContent: |-
    env:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: auth.k8s.localdev    
    selfSigned: false
    certSecretName: ingress-certs
    ingress:
      enabled: true
      hostname: auth.k8s.localdev
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "https"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      hosts:
        - host: "auth.k8s.localdev"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ingress-certs
          hosts:
            - auth.k8s.localdev