---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minio
  namespace: helm-controller
spec:
  chart: minio
  repo: https://charts.min.io/
  version: 4.1.0
  targetNamespace: kube-addons
  # https://github.com/minio/minio/blob/master/helm/minio/values.yaml
  valuesContent: |-
    service:
      type: ClusterIP
    rootUser: "admin"
    rootPassword: "adminSecretKey123"
    buckets:
      - name: "k8s"
        policy: k8sPolicy
        purge: false
        versioning: false
        objectlocking: false
    users:
      - accessKey: "k8sAdminAccessKey"
        secretKey: "k8sAdminSecretKey123"
        policy: k8sPolicy
    policies:
      - name: k8sPolicy
        statements:
          - resources:
              - 'arn:aws:s3:::k8s/*'
            actions:
              - "s3:AbortMultipartUpload"
              - "s3:GetObject"
              - "s3:DeleteObject"
              - "s3:PutObject"
              - "s3:ListMultipartUploadParts"
          - resources:
              - 'arn:aws:s3:::k8s'
            actions:
              - "s3:CreateBucket"
              - "s3:GetBucketLocation"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
    mode: standalone
    replicas: 1
    persistence:
      enabled: true
      size: 8Gi
    ingress:
      enabled: true
      path: /
      hosts:
        - minio-client.k8s.localdev
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
    consoleIngress:
      enabled: true
      path: /
      hosts:
        - minio.k8s.localdev
