---
apiVersion: v1
kind: Namespace
metadata:
  name: helm-playground
  labels:
    name: helm-playground
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgresql
  namespace: helm-controller
spec:
  chart: postgresql
  repo: https://charts.bitnami.com/bitnami
  version: 12.2.2
  targetNamespace: helm-playground
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  valuesContent: |-
    global:
      postgresql:
        auth:
          postgresPassword: "postgres-pwd"
          username: "datasets_user"
          password: "datasets_pwd"
          database: "datasets_db"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: haproxy
  namespace: helm-controller
spec:
  chart: haproxy
  repo: https://haproxytech.github.io/helm-charts
  version: 1.18.0
  targetNamespace: helm-playground
  # https://github.com/haproxytech/helm-charts/blob/main/haproxy/values.yaml
  valuesContent: |-
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: haproxy.k8s.localdev
      config: |
        global
          log stdout format raw local0
          maxconn 1024
        defaults
          log global
          timeout client 60s
          timeout connect 60s
          timeout server 60s

        frontend postgresql
          bind *:5432
          mode tcp
          default_backend postgresql

        backend postgresql
          mode tcp
          balance roundrobin
          server postgresql:5432