version: "3.9"
services:
  server:
    image: gocd/gocd-server-centos-9:v23.1.0
    ports:
      - "8153:8153"
    environment:
      - GO_SERVER_SYSTEM_PROPERTIES=-Dgo.database.provider=com.thoughtworks.go.postgresql.PostgresqlDatabase
      - GOCD_PLUGIN_INSTALL_docker-registry-artifact-plugin=https://github.com/gocd/docker-registry-artifact-plugin/releases/download/v1.3.1-440/docker-registry-artifact-plugin-1.3.1-440.jar
      - GOCD_PLUGIN_INSTALL_gocd-git-path-material-plugin=https://github.com/TWChennai/gocd-git-path-material-plugin/releases/download/v2.2.2-262/gocd-git-path-material-plugin-2.2.2-262.jar
      - GOCD_PLUGIN_INSTALL_gocd-git-feature-branch-plugin=https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/download/v1.3.5/git-fb-poller-1.3.5.jar
      - GOCD_PLUGIN_INSTALL_s3-artifact-plugin=https://github.com/Diogomrol/gocd-s3-artifact-plugin/releases/download/v1.0/s3-artifact-plugin-1.0.0-12.jar
    volumes:
      - gocd_data:/godata
      - ./docker-entrypoint.d/server:/docker-entrypoint.d
      - ./xconfig:/xconfig
      - ./xsecret:/xsecret
    depends_on:
      - "db"
    networks:
      - gocd-network
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gocd
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - gocd_db:/var/lib/postgresql/data
    networks:
      - gocd-network
  agent:
    build:
      context: .
      dockerfile: agent.dockerfile
    privileged: true
    environment:
      - GO_SERVER_URL=http://server:8153/go
      - AGENT_AUTO_REGISTER_KEY=f8b0da76-7b1d-4b45-849d-3a117c70cb2b
    depends_on:
      - "server"
    deploy:
      replicas: 2
    volumes:
      - ./docker-entrypoint.d/agent:/docker-entrypoint.d
    networks:
      - gocd-network
  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    networks:
      - gocd-network
  sonarqube-db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_postgresql_data:/var/lib/postgresql/data
    networks:
      - gocd-network
volumes:
  gocd_data:
  gocd_db:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_postgresql_data:
networks:
  gocd-network: